In [1]:
import pandas as pd

In [9]:
baseline_scd = pd.read_csv("resultados-exp-01-base-dblp.csv")
baseline_ncvr = pd.read_csv("resultados-exp-01-base-ncvoter.csv")
baseline_music = pd.read_csv("resultados-exp-01-base-musicbrainz.csv")

In [ ]:
def media_e_desvio_padrao(df):
    colunas_numericas = df.select_dtypes(include="number")
    return pd.DataFrame({
        "media": colunas_numericas.mean(),
        "desvio_padrao": colunas_numericas.std()
    })

In [13]:
baseline_scd.head(1)

,blocking_s,matching_s,tp,fp,pairs_no,recall,precision,replica,seed
0,6.126161,156.082741,4983,70138,75121,0.931924,0.066333,1,20260907

In [12]:
media_e_desvio_padrao(baseline_scd)

                   media  desvio_padrao
blocking_s  5.743406e+00       0.136745
matching_s  1.558559e+02       1.416995
tp          4.978200e+03       4.732864
fp          7.054890e+04    1044.727976
pairs_no    7.552710e+04    1044.154038
recall      9.310267e-01       0.000885
precision   6.592427e-02       0.000926
replica     5.500000e+00       3.027650
seed        2.026091e+07       3.027650